INSERT INTO author(name)
VALUES ('Johnny Lennon'),
        ('Freddie Mercury'),
        ('Amy Winehouse'),
        ('Bob Marley'),
        ('Elvis Presley'),
        ('MJ Jackson'),
        ('Queen Aretha'),
        ('Kurt Cobain'),
        ('Beyoncé Knowles'),
        ('Ziggy Stardust'),
        ('Becky G'),
        ('Pitbull'),
        ('The Black Eyed Peas'),
        ('Maroon 5'),
        ('The Weeknd'),
        ('Red Hot Chili Peppers'),
        ('Imagine Dragons'),
        ('Coldplay'),
        ('The Rolling Stones'),
        ('Metallica');